import { Project } from '@/types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'url-shortener',
    name: 'URL Shortener',
    description: 'Create short links with click analytics and country stats.',
    longDescription: 'A fast URL shortener running on Cloudflare Workers with KV storage. Tracks total clicks, last 24 hours, countries, and devices.',
    tag: 'API',
    day: 1,
    status: 'live',
    url: '/projects/url-shortener',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '2',
    slug: 'dead-man-switch',
    name: 'Dead Man Switch',
    description: 'Encrypt secrets that auto-decrypt if you stop checking in.',
    longDescription: 'A zero-knowledge dead man switch built on Cloudflare Workers. Encrypt a message that will only be revealed if you stop checking in within a set interval.',
    tag: 'Security',
    day: 2,
    status: 'live',
    url: '/projects/dead-man-switch',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '3',
    slug: 'dynamic-og-images',
    name: 'Dynamic OG Images',
    description: 'Generate open graph images on the edge for any page.',
    longDescription: 'Generate beautiful, dynamic Open Graph images on Cloudflare Workers edge nodes. Pass a title and description as query params and get a ready-to-use OG image.',
    tag: 'Generator',
    day: 3,
    status: 'live',
    url: '/projects/dynamic-og-images',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '4',
    slug: 'hire-wire',
    name: 'Hire Wire',
    description: 'Parse and score resumes against job descriptions instantly.',
    longDescription: 'Upload a resume and paste a job description — Hire Wire scores the match and highlights missing keywords using Cloudflare Workers AI.',
    tag: 'AI',
    day: 4,
    status: 'live',
    url: '/projects/hire-wire',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '5',
    slug: 'url-metadata-api',
    name: 'URL Metadata API',
    description: 'Fetch open graph, Twitter card, and meta tags from any URL.',
    longDescription: 'Scrape Open Graph, Twitter Card, and standard meta tags from any URL via a simple API. Runs on Cloudflare Workers for global low latency.',
    tag: 'API',
    day: 5,
    status: 'live',
    url: '/projects/url-metadata-api',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '6',
    slug: 'redirect-chain-tracer',
    name: 'Redirect Chain Tracer',
    description: 'Trace every hop in a redirect chain with timing and params.',
    longDescription: 'Follow every redirect hop from a URL, capturing HTTP status codes, timing, added/removed query params, and protocol downgrades.',
    tag: 'Debug',
    day: 6,
    status: 'live',
    url: '/projects/redirect-chain-tracer',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '7',
    slug: 'apithrottle',
    name: 'API Throttle',
    description: 'Rate-limit any API endpoint with a simple proxy layer.',
    longDescription: 'Add rate limiting to any upstream API with a Cloudflare Workers proxy. Configure limits per IP, per token, or globally.',
    tag: 'API',
    day: 7,
    status: 'live',
    url: '/projects/apithrottle',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '8',
    slug: 'webdigest',
    name: 'Web Digest',
    description: 'Summarize any webpage into key takeaways using AI.',
    longDescription: 'Paste any URL and get an AI-generated summary and bullet-point takeaways powered by Cloudflare Workers AI.',
    tag: 'AI',
    day: 8,
    status: 'live',
    url: '/projects/webdigest',
    github: 'https://github.com/mdanassaif/workerscando',
  },
  {
    id: '9',
    slug: 'doctomd',
    name: 'DocToMD',
    description: 'Convert any file — PDF, Word, Excel, images — to clean Markdown instantly.',
    longDescription: 'Drop any document or image and get clean Markdown back in milliseconds. Powered by Workers AI toMarkdown — supports PDF, DOCX, XLSX, ODS, HTML, XML, CSV, JPEG, PNG, WebP, and SVG.',
    tag: 'AI',
    day: 9,
    status: 'live',
    url: '/projects/doctomd',
    github: 'https://github.com/mdanassaif/workerscando',
  },
];

export function getLiveProjects(): Project[] {
  return projects.filter((p) => p.status === 'live');
}
